### ISSUE TITLE
Presence does not appear on discord

### ISSUE THREAD

**Issue by tecosaur** [Izumemori/muscord-cpp#1]
Hello,

Thought this looks good, and I'd try it out. Unfortunately, while the log looks fine, no discord presence appears :(
```
[INFO] Connecting...
[INFO] Logged in as tecosaur#ABCD (≪SOMENUMBERSHERE≫)
[INFO] [Lollypop] [PLAYING] Crowded House - Fingers of Love
```

It would be nice if this worked :)

_p.s. as a feature request, do you know if it might be possible to set the icon to the album art?_

**Comment by tecosaur** [comment]
Ooops, this was a big mistake on my part, I'd turned off "Game activity" :sweat_smile:

**Comment by Izumemori** [comment]
Glad you solved it, sadly it's not possible to update the album art, it's a restriction imposed by discord.
